from sqlalchemy.orm import Session

def test_product_owners_no_transactions(sql_session: Session) -> None: ...
def test_product_owners_add_products(sql_session: Session) -> None: ...
def test_product_owners_add_and_buy_products(sql_session: Session) -> None: ...
def test_product_owners_add_and_throw_products(sql_session: Session) -> None: ...
def test_product_owners_multiple_users(sql_session: Session) -> None: ...
def test_product_owners_adjust_stock_down(sql_session: Session) -> None: ...
def test_product_owners_adjust_stock_up(sql_session: Session) -> None: ...
def test_product_owners_negative_stock(sql_session: Session) -> None: ...
def test_product_owners_add_products_from_negative_stock(sql_session: Session) -> None: ...
def test_product_owners_interleaved_users(sql_session: Session) -> None: ...
